kind: Deployment
apiVersion: apps/v1
metadata:
  name: dc-socket-manager
  namespace: dc-socket-manager
  labels:
    app: dc-socket-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dc-socket-manager
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dc-socket-manager
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: dc-socket-manager
          env:        
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: dc-socket-manager
                  key: PORT
            - name: UI_PORT
              valueFrom:
                configMapKeyRef:
                  name: dc-socket-manager
                  key: UI_PORT
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          securityContext: {}
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            quay.io/rciots/dc-socket-manager:latest
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600